version: '3.4'

services:
  #db:
  #  image: mysql:8.0
  #  cap_add:
  #    - SYS_NICE
  #  restart: always
  #  environment:
  #    - MYSQL_DATABASE=activities_mini
  #    - MYSQL_ROOT_PASSWORD=123456
  #  ports:
  #    - '3306:3306'
  #  volumes:
  #    - db:/var/lib/mysql
  #    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

  Activities.Mini.IdentityServer:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}activitiesminiidentityserver
    build:
      context: .
      dockerfile: src/Activities.Mini.IdentityServer/Dockerfile
    ports:
      - 44344:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Activities.Mini.IdentityServer.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
        #- $env:APPDATA\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        #- $env:USERPROFILE\.aspnet\https:/root/.aspnet/https/   

  activities.mini.httpapi.host:
    container_name: activity-api
    image: ${DOCKER_REGISTRY-}activitiesminihttpapihost
    build:
      context: .
      dockerfile: src/Activities.Mini.HttpApi.Host/Dockerfile
    ports:
      - 44310:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Activities.Mini.HttpApi.Host.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
        #- $env:APPDATA\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        #- $env:USERPROFILE\.aspnet\https:/root/.aspnet/https/
#volumes:
#  db:
#    driver: local

